In [120]:
import pandas as pd
PATH_HAIKU = '../data/m_haiku.json'
df = pd.read_json(PATH_HAIKU)

In [123]:
len(df["id"].unique())

34831

In [137]:
df[df.duplicated(subset='id', keep="last")].head(200)

          id          content author      data_from
2939   21699  児等の顔映して消えししやぼん玉    伊藤和  haiku-data.jp
2940   21697      朧夜の面影橋を渡りけり    伊藤和  haiku-data.jp
2941   21700     碧空をきりりと裂きて初燕    伊藤和  haiku-data.jp
2942   21698       老鶯の声も緑に美術館    伊藤和  haiku-data.jp
2943   21701     花筏よろめきあひて水の旅    伊藤和  haiku-data.jp
...      ...              ...    ...            ...
33607   4301   桃冷す水しろがねにうごきけり  百合山羽公  haiku-data.jp
33608   4300    海道を好みて走るいなびかり  百合山羽公  haiku-data.jp
33609  39939    花盗人ちりくる花を仰ぎけり  百合山羽公  haiku-data.jp
33610  39941   茶の花のかげのきてゐる囮かな  百合山羽公  haiku-data.jp
33611  39942   顔あげて茅花の中の鹿の子かな  百合山羽公  haiku-data.jp

[131 rows x 4 columns]

In [134]:
df[df["id"] == 21699]

         id          content author      data_from
2939  21699  児等の顔映して消えししやぼん玉    伊藤和  haiku-data.jp
2945  21699  児等の顔映して消えししやぼん玉   伊藤和子  haiku-data.jp

In [125]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34962 entries, 0 to 34961
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         34962 non-null  int64
 1   content    34962 non-null  object
 2   author     34962 non-null  object
 3   data_from  34962 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.1+ MB

In [48]:
from transformers import BertJapaneseTokenizer, BertModel


import torch
import numpy as np

MODEL_NAME = "sonoisa/sentence-bert-base-ja-mean-tokens-v2"
tokenizer = BertJapaneseTokenizer.from_pretrained(MODEL_NAME)
model = BertModel.from_pretrained(MODEL_NAME)

c:\workspace\hAIku\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [80]:
max_length = 256
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

def sentence_to_vector(sentence):
  encoding = tokenizer(
    sentence,
    max_length = max_length,
    padding = 'max_length',
    truncation = True,
    return_tensors = 'pt'
  )
  encoding = {k: v.to(device) for k, v in encoding.items()}
  attention_mask = encoding['attention_mask']

  #文章ベクトルを計算
  with torch.no_grad():
    output = model(**encoding)
    last_hidden_state = output.last_hidden_state
    averaged_hidden_state =(last_hidden_state*attention_mask.unsqueeze(-1)).sum(1)/attention_mask.sum(1,keepdim=True) 

  return averaged_hidden_state

def calc_similarity(sentence_vector1):
  ret_func = lambda sentence_vector2: torch.nn.functional.cosine_similarity(sentence_vector1, sentence_vector2, dim=1).detach().cpu().numpy().copy()[0]
  return ret_func

In [84]:
df = df.head(100)
df["content_vector"] = df["content"].apply(sentence_to_vector)

In [81]:
haiku_konbu = "流れつくこんぶに何が書いてあるか"
vec_konbu = sentence_to_vector(haiku_konbu)

In [82]:
calc_similarity(vec_konbu)(df["content_vector"][0])

0.061894618

In [85]:
calc_func = calc_similarity(vec_konbu)

df["similarity"] = df["content_vector"].apply(calc_func)

In [86]:
df

,id,content,author,data_from,content_vector,similarity
0,12716,若草や杖の穴より湧く温泉,相生緑葉,haiku-data.jp,"[[tensor(0.3880), tensor(-0.5346), tensor(-1.7...",0.061895
1,1416,ふらふらと死にゐし風が起き上る,相生垣瓜人,haiku-data.jp,"[[tensor(0.9668), tensor(-0.0035), tensor(0.32...",0.221810
2,1417,わが宿のいささ群竹酔ふ日かも,相生垣瓜人,haiku-data.jp,"[[tensor(-0.1582), tensor(-0.7197), tensor(-0....",0.232927
3,1425,クリスマス佛は薄目し給へり,相生垣瓜人,haiku-data.jp,"[[tensor(-1.4064), tensor(0.7763), tensor(-1.7...",0.171127
4,1419,一団の年賀状にぞ襲はれし,相生垣瓜人,haiku-data.jp,"[[tensor(-0.4190), tensor(-0.0145), tensor(-0....",0.435895
...,...,...,...,...,...,...
95,30139,先生とその先生に岬東風,青木伊佐恵,haiku-data.jp,"[[tensor(0.4793), tensor(0.3892), tensor(-0.65...",0.105850
96,30140,四阿の会話二言雨遍路,青木伊佐恵,haiku-data.jp,"[[tensor(-1.2596), tensor(-0.5257), tensor(-0....",0.164757
97,30138,特攻の島けぶりおり芽木の島,青木伊佐恵,haiku-data.jp,"[[tensor(0.1202), tensor(0.1482), tensor(-0.64...",0.195129
98,30142,碧眼の少年と見る原爆樹,青木伊佐恵,haiku-data.jp,"[[tensor(-0.4134), tensor(-0.0790), tensor(-0....",0.082512
99,30141,稲刈って千の石垣あらわれし,青木伊佐恵,haiku-data.jp,"[[tensor(-1.2672), tensor(-0.3551), tensor(-0....",0.222112

In [88]:
df.sort_values('similarity', ascending=False)

,id,content,author,data_from,content_vector,similarity
4,1419,一団の年賀状にぞ襲はれし,相生垣瓜人,haiku-data.jp,"[[tensor(-0.4190), tensor(-0.0145), tensor(-0....",0.435895
24,1410,隙間風その数条を熟知せり,相生垣瓜人,haiku-data.jp,"[[tensor(0.0624), tensor(0.6305), tensor(-0.00...",0.366566
6,1415,何物が蛾を装ひて入り来るや,相生垣瓜人,haiku-data.jp,"[[tensor(-0.7189), tensor(-0.1740), tensor(0.4...",0.357818
92,26169,氷紋をなぞった指の行方かな,青木章子,haiku-data.jp,"[[tensor(-0.3852), tensor(0.1366), tensor(0.40...",0.349299
79,29174,指切りの針いっぽんが朧なり,相本寿美子,haiku-data.jp,"[[tensor(0.0033), tensor(-0.7605), tensor(-0.4...",0.318885
...,...,...,...,...,...,...
51,19022,盆梅に一湾据えて漁夫の婚,會田渓泉,haiku-data.jp,"[[tensor(0.1379), tensor(-0.0225), tensor(-1.1...",0.015112
18,1409,梅雨明けぬ猫がまづ木に駈け上がる,相生垣瓜人,haiku-data.jp,"[[tensor(0.1205), tensor(0.5899), tensor(-0.25...",0.006559
5,1426,亡き母に米寿の春を贈られし,相生垣瓜人,haiku-data.jp,"[[tensor(0.6411), tensor(-0.7814), tensor(-0.0...",0.006354
88,14477,春の雲キリンの首がさびしがる,相吉香湖,haiku-data.jp,"[[tensor(0.0390), tensor(1.0330), tensor(-0.05...",-0.021235
62,29787,ヒロシマや開いて閉じて傘立てへ,相原左義長,haiku-data.jp,"[[tensor(-0.1307), tensor(-0.1228), tensor(-0....",-0.025517

In [90]:
import os
import pickle
with open(os.path.join("storage", "haiku"), mode='wb') as f:
  pickle.dump(df, f, protocol=2)

In [91]:

with open(os.path.join("storage", "haiku"), 'rb') as f:
  mydata2 = pickle.load(f)
mydata2

,id,content,author,data_from,content_vector,similarity
0,12716,若草や杖の穴より湧く温泉,相生緑葉,haiku-data.jp,"[[tensor(0.3880), tensor(-0.5346), tensor(-1.7...",0.061895
1,1416,ふらふらと死にゐし風が起き上る,相生垣瓜人,haiku-data.jp,"[[tensor(0.9668), tensor(-0.0035), tensor(0.32...",0.221810
2,1417,わが宿のいささ群竹酔ふ日かも,相生垣瓜人,haiku-data.jp,"[[tensor(-0.1582), tensor(-0.7197), tensor(-0....",0.232927
3,1425,クリスマス佛は薄目し給へり,相生垣瓜人,haiku-data.jp,"[[tensor(-1.4064), tensor(0.7763), tensor(-1.7...",0.171127
4,1419,一団の年賀状にぞ襲はれし,相生垣瓜人,haiku-data.jp,"[[tensor(-0.4190), tensor(-0.0145), tensor(-0....",0.435895
...,...,...,...,...,...,...
95,30139,先生とその先生に岬東風,青木伊佐恵,haiku-data.jp,"[[tensor(0.4793), tensor(0.3892), tensor(-0.65...",0.105850
96,30140,四阿の会話二言雨遍路,青木伊佐恵,haiku-data.jp,"[[tensor(-1.2596), tensor(-0.5257), tensor(-0....",0.164757
97,30138,特攻の島けぶりおり芽木の島,青木伊佐恵,haiku-data.jp,"[[tensor(0.1202), tensor(0.1482), tensor(-0.64...",0.195129
98,30142,碧眼の少年と見る原爆樹,青木伊佐恵,haiku-data.jp,"[[tensor(-0.4134), tensor(-0.0790), tensor(-0....",0.082512
99,30141,稲刈って千の石垣あらわれし,青木伊佐恵,haiku-data.jp,"[[tensor(-1.2672), tensor(-0.3551), tensor(-0....",0.222112

In [105]:

with open(os.path.join("storage", "tokenizer.pkl"), mode='wb') as f:
  pickle.dump(tokenizer, f, protocol=2)

In [106]:

with open(os.path.join("storage", "model.pkl"), mode='wb') as f:
  pickle.dump(model, f, protocol=2)

In [107]:

with open(os.path.join("..", "data", "model.pkl"), 'rb') as f:
  model = pickle.load(f)
with open(os.path.join("..", "data", "tokenizer.pkl"), 'rb') as f:
  tokenizer = pickle.load(f)

In [97]:

with open(os.path.join("..", "data", "haiku_vector.pkl"), 'rb') as f:
  open_haiku_vector = pickle.load(f)
open_haiku_vector.head(10)

      id                                     content_vector
0  12716  [[0.3880200684070587, -0.5346135497093201, -1....
1   1416  [[0.9667874574661255, -0.0034706180449575186, ...
2   1417  [[-0.1582280993461609, -0.7196993231773376, -0...
3   1425  [[-1.4064396619796753, 0.7762742638587952, -1....
4   1419  [[-0.41900748014450073, -0.014512510970234871,...
5   1426  [[0.6410695314407349, -0.7813975811004639, -0....
6   1415  [[-0.7188867330551147, -0.17399494349956512, 0...
7   1420  [[0.533454954624176, -0.09149239212274551, 0.3...
8   1418  [[-0.1615806519985199, 0.7083917856216431, 0.4...
9   1408  [[1.184794545173645, 0.9602559804916382, -0.95...

In [98]:
open_haiku_vector["content_vector"][0]

[[0.3880200684070587,
  -0.5346135497093201,
  -1.7283945083618164,
  0.29024991393089294,
  0.3231339156627655,
  -0.8004710078239441,
  1.0436722040176392,
  -0.13755503296852112,
  -0.4383918046951294,
  -0.17729811370372772,
  0.48080864548683167,
  -0.020076552405953407,
  0.052380066365003586,
  0.5927050709724426,
  1.5720373392105103,
  0.14987507462501526,
  0.5794453024864197,
  0.2039673775434494,
  0.4256622791290283,
  0.7358224987983704,
  -0.029036492109298706,
  0.01783769764006138,
  -0.06384135037660599,
  0.2267109602689743,
  -0.013813957571983337,
  0.9159336090087891,
  -0.1927061825990677,
  -0.5525330305099487,
  0.44109055399894714,
  0.5030291676521301,
  -0.2667377293109894,
  -0.38371291756629944,
  0.3010387420654297,
  0.9484040141105652,
  0.14990437030792236,
  -0.4770948886871338,
  -0.5033867955207825,
  -0.15734614431858063,
  0.04777047038078308,
  -0.35067903995513916,
  0.002345845103263855,
  0.2525540292263031,
  -1.3388938903808594,
  -0.036995913833379745,
  -0.9716277718544006,
  0.05367973819375038,
  -0.23638981580734253,
  0.7071372866630554,
  -0.37950825691223145,
  -0.32259735465049744,
  -0.5471283793449402,
  -0.0880628153681755,
  0.40853020548820496,
  -0.14616794884204865,
  0.5177904963493347,
  -0.27553805708885193,
  0.9107921719551086,
  -0.7237743735313416,
  0.7482859492301941,
  -0.060419630259275436,
  -0.11475684493780136,
  0.4337655305862427,
  0.3801143169403076,
  0.0017243673792108893,
  -0.7406430244445801,
  -0.1970169097185135,
  0.1777402013540268,
  -0.13584239780902863,
  -0.6374565958976746,
  -0.02312488667666912,
  -0.6685717105865479,
  0.559235692024231,
  -0.3699587285518646,
  0.19217483699321747,
  1.0257710218429565,
  0.4100598394870758,
  0.8460739254951477,
  0.20976662635803223,
  0.04544447362422943,
  0.2921057343482971,
  -0.9658780097961426,
  0.49477383494377136,
  -0.12134482711553574,
  -0.3728543519973755,
  0.8715014457702637,
  0.26280677318573,
  0.975928008556366,
  -0.7834592461585999,
  -0.5579378008842468,
  1.0489178895950317,
  -0.7001754641532898,
  0.10314196348190308,
  0.6685214042663574,
  -0.062235910445451736,
  -0.46552976965904236,
  0.216653510928154,
  0.6489174365997314,
  -0.5111958384513855,
  0.24542224407196045,
  0.7109063267707825,
  -0.5175526142120361,
  -0.1214442253112793,
  0.6132039427757263,
  -0.6685027480125427,
  0.6967084407806396,
  -0.8976529240608215,
  -0.6059656143188477,
  -0.44237783551216125,
  0.1552714705467224,
  -0.9737094044685364,
  0.28072279691696167,
  -0.285831481218338,
  -0.42496708035469055,
  1.2100318670272827,
  -0.6241268515586853,
  -0.8489952087402344,
  0.5183413624763489,
  -0.6133638024330139,
  -0.46115341782569885,
  -0.24693769216537476,
  -0.04923113062977791,
  -1.0196338891983032,
  -0.6556373834609985,
  0.22381162643432617,
  -0.20196235179901123,
  0.4220256805419922,
  0.08795531839132309,
  0.9018504023551941,
  -0.3126472234725952,
  0.3515201807022095,
  -0.3265927731990814,
  0.8734784722328186,
  0.5833271145820618,
  0.31859228014945984,
  -0.36429181694984436,
  -0.09752955287694931,
  -0.36645379662513733,
  -0.2890838086605072,
  -0.7909477353096008,
  -0.2723116874694824,
  -0.4036906957626343,
  -0.14843875169754028,
  -0.2802943289279938,
  0.08410502225160599,
  -0.12601889669895172,
  -0.4652988612651825,
  -0.6832494735717773,
  -0.8078467845916748,
  -0.7668775916099548,
  -0.0731341764330864,
  -0.1174040362238884,
  0.6395569443702698,
  1.166845440864563,
  0.5235256552696228,
  -0.3469024896621704,
  1.4090490341186523,
  -0.306503564119339,
  -1.0527644157409668,
  0.9247809052467346,
  -0.48659026622772217,
  -0.03892460837960243,
  -0.938713014125824,
  0.3819315433502197,
  -1.3957124948501587,
  0.22325770556926727,
  -0.03561696037650108,
  0.5967969298362732,
  0.8867473602294922,
  -0.4400155246257782,
  0.6953673362731934,
  0.10393460839986801,
  -0.05099351704120636,
  -0.5893818736076355,
  0.27096542716026306,
  0.21413731575012207,
  1.418235182762146,
  -0.4650104343891144,
  0.06875097751617432,
  0.5077688694000244,
  1.2934149503707886,
  -0.40934181213378906,
  -0.3663894236087799,
  -0.8812404274940491,
  -1.0238796472549438,
  0.28955078125,
  1.231858253479004,
  1.0708309412002563,
  0.13331352174282074,
  -0.6864125728607178,
  -0.8119543194770813,
  1.9314936399459839,
  -0.0686117634177208,
  0.2993680238723755,
  -0.4800647795200348,
  -0.24255119264125824,
  0.5518460869789124,
  0.18587906658649445,
  0.7011038661003113,
  0.22163493931293488,
  1.1159018278121948,
  0.33911123871803284,
  -0.4623982012271881,
  -0.012505303137004375,
  -0.07560684531927109,
  1.1336679458618164,
  -1.8018027544021606,
  -0.936504065990448,
  -0.06353583186864853,
  -0.468813419342041,
  1.0444453954696655,
  0.7961555123329163,
  0.36405912041664124,
  -0.0762120932340622,
  1.1779979467391968,
  0.5406587719917297,
  0.07745163887739182,
  -1.0906225442886353,
  0.4062289297580719,
  -0.1375587284564972,
  -0.8977055549621582,
  0.12563884258270264,
  -0.682457447052002,
  1.506766676902771,
  -0.9852523803710938,
  0.46912920475006104,
  0.054472606629133224,
  -1.1471673250198364,
  0.2999536693096161,
  0.920710563659668,
  0.13804560899734497,
  -0.3807002007961273,
  0.006075233221054077,
  -0.472843736410141,
  0.5549336075782776,
  1.2268080711364746,
  -0.010179336182773113,
  -0.7562307715415955,
  -0.48787394165992737,
  1.5829099416732788,
  0.04991697147488594,
  -0.3469255864620209,
  0.45015931129455566,
  -0.14348721504211426,
  0.02024935744702816,
  0.3342403173446655,
  -0.4815613031387329,
  -0.5806900858879089,
  0.6518574953079224,
  0.004459691699594259,
  -0.12375769764184952,
  0.6810674667358398,
  0.4476478099822998,
  -0.6636978983879089,
  -0.29592812061309814,
  0.08528485149145126,
  -0.35667160153388977,
  -0.13851696252822876,
  -0.7275748252868652,
  -0.9632361531257629,
  0.7433069348335266,
  -0.802920401096344,
  0.0690024122595787,
  1.133060336112976,
  -0.28828415274620056,
  0.3961801826953888,
  -0.24809110164642334,
  1.37299644947052,
  0.4085749089717865,
  -0.23941917717456818,
  -0.4889965057373047,
  1.0092695951461792,
  -0.06586123257875443,
  0.0854787826538086,
  0.6769204139709473,
  0.11462745070457458,
  0.15427611768245697,
  -0.36598679423332214,
  -0.5547472834587097,
  -0.30135393142700195,
  -0.41545605659484863,
  -0.11508893966674805,
  0.1480187624692917,
  -0.5759702920913696,
  -0.34716716408729553,
  -0.4524448812007904,
  -0.6609615683555603,
  -0.590578556060791,
  0.1790909618139267,
  0.10027006268501282,
  -0.47157931327819824,
  0.3862020969390869,
  -0.5757526159286499,
  -0.8911396861076355,
  0.33750781416893005,
  0.5356019139289856,
  0.39126336574554443,
  -0.2823253571987152,
  -0.5786665081977844,
  0.26182013750076294,
  0.27523794770240784,
  0.07061358541250229,
  -1.005906343460083,
  -0.38786736130714417,
  1.2731701135635376,
  0.1410684436559677,
  0.9003183245658875,
  -0.34738287329673767,
  0.026646122336387634,
  -0.42483922839164734,
  0.1656426340341568,
  -0.23600776493549347,
  0.19640801846981049,
  -0.19777409732341766,
  0.4620682895183563,
  0.699495792388916,
  -1.1922693252563477,
  -0.26568663120269775,
  -0.004288194235414267,
  0.740684449672699,
  -0.780687153339386,
  -0.4098283052444458,
  -0.06369053572416306,
  0.1461242437362671,
  -0.2370266169309616,
  0.27488958835601807,
  0.6147933602333069,
  0.47114357352256775,
  0.07478056848049164,
  -0.27898240089416504,
  0.05862177535891533,
  -0.4826070964336395,
  0.744049072265625,
  -0.04944834113121033,
  -0.9039137959480286,
  0.13851453363895416,
  0.5729351043701172,
  0.4912865161895752,
  -0.14180520176887512,
  -0.623636782169342,
  0.1347097009420395,
  -0.7581391334533691,
  0.7342278361320496,
  -0.9261279106140137,
  0.059552788734436035,
  -0.14737671613693237,
  -0.6459073424339294,
  0.3163604438304901,
  -0.10747351497411728,
  -0.08723903447389603,
  0.3948952853679657,
  0.1771858185529709,
  0.049398619681596756,
  0.5996217131614685,
  0.21404512226581573,
  1.133273959159851,
  0.9025514721870422,
  -0.4607928693294525,
  -1.0545514822006226,
  -0.38831010460853577,
  -0.42371413111686707,
  -0.2596922814846039,
  -0.20246672630310059,
  -0.6046266555786133,
  1.2685080766677856,
  -0.5875630378723145,
  1.0805813074111938,
  -0.15861573815345764,
  0.08398663997650146,
  -0.19697217643260956,
  -0.1259610652923584,
  -0.9291183948516846,
  -0.05172692611813545,
  -0.28612884879112244,
  0.9822924733161926,
  0.03670082613825798,
  0.8210651874542236,
  0.15231002867221832,
  0.06128665804862976,
  -0.12116372585296631,
  -0.6559438109397888,
  -0.05929620936512947,
  1.121628999710083,
  0.5678195953369141,
  -0.15467694401741028,
  0.3458028733730316,
  0.19333605468273163,
  0.2255394458770752,
  0.015311062335968018,
  -0.13319873809814453,
  -0.9087624549865723,
  -0.43883243203163147,
  -0.7098610997200012,
  -0.07369019836187363,
  0.397610068321228,
  -0.2310413271188736,
  -0.22312867641448975,
  -0.0797472894191742,
  0.5377864837646484,
  0.31331515312194824,
  0.24592316150665283,
  0.2997281849384308,
  0.6184184551239014,
  0.5553033351898193,
  -0.007798562292009592,
  0.04734490439295769,
  -0.25905027985572815,
  0.12510477006435394,
  -0.3415980041027069,
  -0.6059586405754089,
  0.30249395966529846,
  0.1023450717329979,
  0.3035486936569214,
  -0.30055972933769226,
  0.2364993840456009,
  -0.3465500771999359,
  0.27300384640693665,
  0.3732726275920868,
  0.6299893260002136,
  0.7582201957702637,
  -0.2953590452671051,
  0.9448285102844238,
  0.5916167497634888,
  0.1668217033147812,
  0.10283879190683365,
  -0.3026481866836548,
  0.0010543068638071418,
  0.34284770488739014,
  -0.45905473828315735,
  0.4730461835861206,
  0.05445905029773712,
  1.232204794883728,
  -0.5741724371910095,
  0.0166656281799078,
  0.6381311416625977,
  -0.08983544260263443,
  -0.005734796170145273,
  -0.7083747386932373,
  0.6412100195884705,
  -0.6324964165687561,
  0.4607897102832794,
  -1.22650945186615,
  0.63308185338974,
  0.982283890247345,
  0.2755095958709717,
  0.0004514455795288086,
  0.5050780177116394,
  0.20893464982509613,
  0.4206535816192627,
  0.33687910437583923,
  -0.057922665029764175,
  -0.2725277245044708,
  0.4144533574581146,
  -0.347122460603714,
  1.2270325422286987,
  0.2710030972957611,
  0.039258141070604324,
  0.3623330593109131,
  -0.9626162648200989,
  -0.4376383125782013,
  0.6765816807746887,
  -0.007283384446054697,
  0.9439583420753479,
  0.4398312568664551,
  0.19040431082248688,
  0.727637767791748,
  -1.1170090436935425,
  -1.1040902137756348,
  -0.2150402069091797,
  -1.2097750902175903,
  0.47600874304771423,
  -0.08055282384157181,
  -0.7793681025505066,
  0.8258719444274902,
  -0.09466972947120667,
  0.12000527232885361,
  0.11591416597366333,
  0.4286510646343231,
  -0.15484710037708282,
  -0.2041204571723938,
  0.22334139049053192,
  -0.6217727065086365,
  0.36853423714637756,
  -0.5144725441932678,
  0.954101026058197,
  -0.5997207760810852,
  0.3244023621082306,
  -1.5243204832077026,
  0.19459332525730133,
  0.8019550442695618,
  -0.6353614926338196,
  -0.7727575302124023,
  -0.6362237930297852,
  -0.807921826839447,
  -0.5548858642578125,
  0.3031647801399231,
  -0.10103078931570053,
  0.2725948095321655,
  1.5785003900527954,
  0.33614468574523926,
  0.7165303230285645,
  -0.07295949012041092,
  0.3424720764160156,
  -0.3009646236896515,
  0.7608944773674011,
  -0.23669342696666718,
  0.22056062519550323,
  0.7535852789878845,
  -0.3655778467655182,
  -0.48265233635902405,
  0.8697425723075867,
  0.07242543250322342,
  -0.601993978023529,
  -0.2480236291885376,
  -0.752260684967041,
  -0.16120852530002594,
  -0.14922963082790375,
  -0.42624378204345703,
  -0.6204410791397095,
  0.8181766867637634,
  0.6999067664146423,
  -0.7702280879020691,
  -0.24616879224777222,
  -0.6025845408439636,
  0.6264526844024658,
  0.2562521994113922,
  -0.1971186399459839,
  0.6610057353973389,
  -1.0204768180847168,
  0.30466511845588684,
  -0.9579641222953796,
  -1.0941864252090454,
  -1.1768317222595215,
  -1.37623929977417,
  1.1877366304397583,
  0.20680369436740875,
  0.8151436448097229,
  0.1113044023513794,
  -0.4667295515537262,
  -0.3584754467010498,
  -0.5269725918769836,
  1.213033676147461,
  0.30574628710746765,
  1.40070378780365,
  -0.2527633011341095,
  -0.5392389893531799,
  -0.7607877850532532,
  -0.860253632068634,
  -0.7103915214538574,
  -0.25368812680244446,
  -0.8592290878295898,
  -0.2746001183986664,
  -0.45303693413734436,
  -0.5512197017669678,
  0.418499618768692,
  -0.628660261631012,
  0.2733098566532135,
  0.2238222360610962,
  0.07855987548828125,
  -0.024499228224158287,
  -0.3973873555660248,
  -0.23940126597881317,
  0.2473801225423813,
  0.1351490467786789,
  0.6227248311042786,
  -1.2472546100616455,
  -0.14508356153964996,
  0.00627397745847702,
  1.0800164937973022,
  -0.11701921373605728,
  1.0583237409591675,
  -0.22341154515743256,
  0.6268153786659241,
  1.026138186454773,
  -0.3256090581417084,
  0.157716765999794,
  0.337947279214859,
  0.36492958664894104,
  1.002035140991211,
  -0.1021764874458313,
  0.6898768544197083,
  -0.9844673275947571,
  -0.5769594311714172,
  -0.6255812644958496,
  -0.34969642758369446,
  -0.05578005313873291,
  -0.25357815623283386,
  -0.6816417574882507,
  1.2410897016525269,
  -0.6981433033943176,
  0.2474016398191452,
  0.2547043263912201,
  -0.005007395055145025,
  0.7544334530830383,
  -0.4207704961299896,
  -0.5023466944694519,
  -0.10667189210653305,
  0.2765291631221771,
  -0.3755830228328705,
  -0.3586616516113281,
  -0.7565102577209473,
  0.9735668301582336,
  0.37621283531188965,
  1.2549253702163696,
  0.2692970335483551,
  -0.21591420471668243,
  -0.6612963080406189,
  1.1091119050979614,
  1.0658586025238037,
  -0.23158900439739227,
  -0.22791004180908203,
  0.6489618420600891,
  0.5587648749351501,
  -0.5754675269126892,
  -0.17985160648822784,
  -0.08167839795351028,
  -0.25187695026397705,
  0.9743949770927429,
  2.4324605464935303,
  -0.5532000064849854,
  0.12037590146064758,
  -0.5172291994094849,
  -0.14104965329170227,
  -0.36162233352661133,
  -0.020544329658150673,
  0.45786991715431213,
  0.15209873020648956,
  -0.13555672764778137,
  0.06467907875776291,
  -0.7010800242424011,
  0.09303281456232071,
  1.2017446756362915,
  0.6625720262527466,
  0.5974195003509521,
  1.372261881828308,
  1.3588672876358032,
  -0.032774850726127625,
  0.41342630982398987,
  0.9526166915893555,
  0.377562016248703,
  0.4848344326019287,
  0.08889099955558777,
  1.14096999168396,
  -0.17995311319828033,
  0.28612464666366577,
  -0.12088516354560852,
  -0.32730135321617126,
  -0.7415210604667664,
  0.3307422399520874,
  0.5223233699798584,
  0.8038894534111023,
  -0.08714378625154495,
  -0.5664122700691223,
  -0.22452683746814728,
  -1.1529124975204468,
  -0.5705016255378723,
  0.3807525336742401,
  -0.5049741864204407,
  -1.0892683267593384,
  0.44624802470207214,
  -0.16890715062618256,
  0.6973252296447754,
  -0.09242022782564163,
  -0.6402328014373779,
  0.5264931917190552,
  -0.17207379639148712,
  -0.795997142791748,
  1.7459354400634766,
  0.8572468161582947,
  -0.4375195801258087,
  -0.08314912766218185,
  0.27965617179870605,
  -0.35383811593055725,
  -1.3407320976257324,
  1.1730382442474365,
  0.7454661726951599,
  0.4171488583087921,
  -0.07495272904634476,
  -0.345428466796875,
  0.7790050506591797,
  -0.08569362759590149,
  0.9513365626335144,
  -0.32327237725257874,
  -0.9638301730155945,
  0.6548499464988708,
  -1.0385308265686035,
  -1.0287712812423706,
  0.4220221936702728,
  -0.9185538291931152,
  -1.0398770570755005,
  0.2862487733364105,
  -0.8688308596611023,
  0.7278946042060852,
  0.2645290493965149,
  1.0942844152450562,
  1.2901726961135864,
  0.45653200149536133,
  -0.020757993683218956,
  -0.1434832066297531,
  -0.23957936465740204,
  -0.716938316822052,
  -0.3158667981624603,
  0.44630780816078186,
  -0.28034234046936035,
  0.5324337482452393,
  1.1456464529037476,
  -0.10825818032026291,
  -1.8372902870178223,
  0.7317972779273987,
  -0.021081998944282532,
  -0.7612659335136414,
  0.00614378834143281,
  -0.5951682925224304,
  0.10995263606309891,
  0.5260393023490906,
  -0.2467757910490036,
  0.012929131276905537,
  -0.08737900853157043,
  0.4927668273448944,
  -0.3753986060619354,
  0.26167652010917664,
  0.49205541610717773,
  -1.0348759889602661,
  0.3195103704929352,
  -0.8607039451599121,
  0.4955913722515106,
  -0.586991012096405,
  -1.2743463516235352,
  -0.4474703073501587,
  -1.0773102045059204,
  0.8178186416625977,
  -0.7239139676094055,
  -1.1326078176498413,
  0.9648306965827942,
  0.8572198748588562,
  0.311793714761734,
  -0.26809191703796387,
  -0.9526588320732117,
  0.8230457305908203,
  -0.2830483615398407,
  -1.1524267196655273,
  0.311913400888443,
  -0.0733645036816597,
  0.1347675323486328,
  0.21774353086948395,
  -0.7792980670928955,
  0.20952683687210083,
  0.07189549505710602,
  -0.8685911297798157,
  -0.15724776685237885,
  0.790606677532196,
  -0.8537065386772156,
  -0.6058827042579651,
  -0.7503711581230164,
  0.8165567517280579,
  -0.49020302295684814,
  0.4091700613498688,
  -0.07324371486902237,
  0.283211886882782,
  -0.14487770199775696,
  -0.11118614673614502,
  0.8965817093849182,
  -1.103874683380127,
  -0.7847678065299988,
  0.9905793070793152,
  -0.5118669867515564,
  0.13993197679519653,
  -0.3943749964237213,
  -0.46208712458610535]]

In [115]:
from torch import Tensor


max_length = 256
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
def sentence_to_vector(sentence):
  encoding = tokenizer(
    sentence,
    max_length = max_length,
    padding = 'max_length',
    truncation = True,
    return_tensors = 'pt'
  )
  encoding = {k: v.to(device) for k, v in encoding.items()}
  attention_mask = encoding['attention_mask']

  #文章ベクトルを計算
  with torch.no_grad():
    output = model(**encoding)
    last_hidden_state = output.last_hidden_state
    averaged_hidden_state =(last_hidden_state*attention_mask.unsqueeze(-1)).sum(1)/attention_mask.sum(1,keepdim=True) 

  return averaged_hidden_state

def calc_similarity(selected_haiku_vectors: list[Tensor]):
  def ret_func(target: list[list[float]]):
    similarities:list[float] = [torch.nn.functional.cosine_similarity(haiku_vector, torch.tensor(target), dim=1).detach().numpy().copy()[0] for haiku_vector in selected_haiku_vectors]
    return sum(similarities) / len(similarities)
  return ret_func

In [118]:
vec_konbu = sentence_to_vector("流れつくこんぶに何が書いてあるか")
vec_mimizu = sentence_to_vector("私より彼女が綺麗糸みみず")
calc_konbu = calc_similarity([vec_konbu, vec_mimizu])
open_haiku_vector["similarity"] = open_haiku_vector["content_vector"].apply(calc_konbu)
open_haiku_vector.sort_values('similarity', ascending=False)

          id                                     content_vector  similarity
1942    8697  [[-1.1777745485305786, -0.7245752811431885, 0....    0.636742
31329  17857  [[-0.23273643851280212, 0.016235461458563805, ...    0.536933
34233  16259  [[-0.40075916051864624, 0.3729219436645508, 0....    0.507121
6360   32724  [[-0.4002126455307007, 0.4062024652957916, -0....    0.502155
12220  23588  [[-0.7139098048210144, -0.7104634642601013, 0....    0.488308
...      ...                                                ...         ...
16937  18530  [[1.1444756984710693, 0.9872925281524658, -0.7...   -0.082188
2001    4207  [[-0.15254409611225128, -0.09699451923370361, ...   -0.082926
31628   7840  [[-0.9630804657936096, 0.11827445030212402, 0....   -0.087551
7515   32302  [[0.6961217522621155, 0.004624891094863415, -1...   -0.097037
30712   5267  [[-0.15319430828094482, 1.0345277786254883, 0....   -0.109328

[34962 rows x 3 columns]